app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('create/', views.PostCreate.as_view(), name='post_create'),
    path('update/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),
    path('delete/<int:pk>/', views.PostDelete.as_view(), name='post_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),  # マイアプリ
]

app/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField('タイトル', max_length=255)

    def __str__(self):
        return self.title

app/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import Post


class PostList(generic.ListView):
    model = Post


class PostCreate(generic.CreateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('app:post_list')

    def form_valid(self, form):
        self.object = post = form.save()
        messages.info(self.request, f'記事を作成しました。 タイトル:{post.title} pk:{post.pk}')
        return redirect(self.get_success_url())


class PostUpdate(generic.UpdateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('app:post_list')

    def form_valid(self, form):
        self.object = post = form.save()
        messages.info(self.request, f'記事を更新しました。 タイトル:{post.title} pk:{post.pk}')
        return redirect(self.get_success_url())


class PostDelete(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('app:post_list')

    def delete(self, request, *args, **kwargs):
        self.object = post = self.get_object()
        message = f'記事を削除しました。 タイトル:{post.title} pk:{post.pk}'
        post.delete()
        messages.info(self.request, message)
        return redirect(self.get_success_url())

templates/app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
<!-- ナビバー部分 -->
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
               data-target="navbar-menu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div id="navbar-menu" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'app:post_list' %}">Home</a>
                <a class="navbar-item" href="{% url 'app:post_create' %}">New</a>
            </div>
        </div>
</nav>

<!-- メッセージフレームワーク -->
{% if messages %}
<div class="container" style="margin-top:1rem;">
    <div class="notification is-info">
        <button class="delete" type="button"></button>
        {% for message in messages %}
        <p> {{ message }}</p>
        {% endfor %}
    </div>
</div>
{% endif %}}


<!-- メインコンテンツ -->
<main>
    {% block content %}{% endblock %}
</main>

<script>
    // notificationを×押下で閉じれるように。
    for (const element of document.querySelectorAll('.notification > .delete')) {
        element.addEventListener('click', e => {
            e.target.parentElement.classList.add('is-hidden');
        });
    }

    // ナビバーの開閉を設定
    for (const element of document.querySelectorAll('.navbar-burger')) {
        const menuId = element.dataset.target;
        const menu = document.getElementById(menuId);
        element.addEventListener('click', e => {
            element.classList.toggle('is-active');
            menu.classList.toggle('is-active');
        });
    }

</script>
</body>
</html>

templates/app/post_confirm_delete.html
{% extends 'app/base.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            <form action="" method="POST">
                <p>{{ post.title }}を削除します。</p>
                <button type="submit" class="button is-danger">送信</button>
                {% csrf_token %}
            </form>
        </div>
    </section>
{% endblock %}

templates/app/post_form.html
{% extends 'app/base.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            <form action="" method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <button type="submit" class="button is-info">送信</button>
            </form>
        </div>
    </section>
{% endblock %}

templates/app/post_list.html
{% extends 'app/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">記事一覧</h1>
        {% for post in post_list %}
        <div class="box">
            <div class="columns">
                <div class="column is-10">
                    <h2>{{ post.title }}</h2>
                </div>
                <div class="column is-2">
                    <a href="{% url 'app:post_update' post.pk %}" class="button is-info">更新</a>
                    <a href="{% url 'app:post_delete' post.pk %}" class="button is-danger">削除</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

{% endblock %}